#!/bin/sh 

#
# Installation script for ensemblseqlaod
#
###########################################################################

Usage=Install

#
#  Function called when the install fails.
#
installFailed ()
{
    echo "Installation Failed: `date`"
    exit 1
}

cd `dirname $0`

#
# establish the config file names
#
COMMON_CONFIG=common.config

# seqload configs
ENSEMBL_PROT_CONFIG=ensembl_proteinseqload.config
ENSEMBL_TRANS_CONFIG=ensembl_transcriptseqload.config

# assocload configs
ENSEMBL_PROT_ASSOCCONFIG=ensembl_proteinassocload.config
ENSEMBL_TRANS_ASSOCCONFIG=ensembl_transcriptassocload.config

#
# Make sure common config file exists and source it
#
if [ -r ${COMMON_CONFIG} ]
then
    echo "Source ${COMMON_CONFIG}"
    . ${COMMON_CONFIG}
else
    echo "Cannot source configuration file: ${COMMON_CONFIG}"
    installFailed
fi

#
# Check to see if this is a development installation
#
DEV=""
if [ "${INSTALL_TYPE}" = "dev" ]
then
    DEV="-d"
fi

#
# run DLAInstall for each configuration file
#
echo 'running DLAINSTALL'

. ensembl_proteinassocload.config 
${DLAINSTALL} ${DEV}

for c in `ls *load.config`
do
    echo "Source ${c}"
    . ${c}
    ${DLAINSTALL} ${DEV} -x
done

